sudo:
  - required

services:
  - docker

env:
  - bro_version: 2.5.3-dev

before_script:
  - curl -L https://github.com/edenhill/librdkafka/archive/v0.11.5.tar.gz -o /tmp/librdkafka-0.11.5.tar.gz
  - tar -xvzf /tmp/librdkafka-0.11.5.tar.gz
  - pushd /tmp/librdkafka-0.11.5 && ./configure --enable-sasl && make && sudo make install && popd

script:
  - docker run -it --rm -v /usr/local/lib:/librdkafka -v `pwd`:/metron-bro-plugin-kafka broplatform/bro:${bro_version} bro_dist=/usr/src/bro LIBRDKAFKA_ROOT=/librdkafka bro-pkg test /metron-bro-plugin-kafka
