version: '2.4'
services:
  zookeeper:
    build: containers/zookeeper
    image: metron-bro-plugin-kafka_zookeeper:latest
  kafka-1:
    build: containers/kafka
    image: metron-bro-plugin-kafka_kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=2
  kafka-2:
    build: containers/kafka
    image: metron-bro-plugin-kafka_kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=2
  zeek:
    build:
      context: ../
      args:
        ZEEK_VERSION: "3.1.3"
        LIBRDKAFKA_VERSION: "1.4.2"
        PLUGIN_VERSION: "${PLUGIN_VERSION}"
    image: metron-bro-plugin-kafka_zeek:latest
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    volumes:
      - "${DATA_PATH}:/root/data"
      - "${TEST_OUTPUT_PATH}:/root/test_output"
      - "${TEST_PATH}:/root/tests"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true

